### ISSUE TITLE
Add search field for languages

### ISSUE THREAD

**Issue by Aga-C** [ManeraKai/simplytranslate-flutter-client#7]
Hi,

It would be very useful to add a search field for a languages lists, especially that there are many languages to choose. Here is an example how it could be done: https://www.woolha.com/tutorials/flutter-using-autocomplete-widget-examples

**Comment by ManeraKai** [comment]
You're right. I've now replaced `Dropdown` menus with searchable menus.

**Comment by Aga-C** [comment]
I think that it could work a bit better. Now user has to delete the whole textbox and write anything to get any suggestions. That's not exactly what I was thinking about. Maybe it would be better if it would select the text on focus, or clear the input on the start. 

Also, there is another option. After some searching, I've found two components for searchable dropdowns for Flutter. I think, one of these would be even better solution:
- https://pub.dev/packages/dropdown_search
- https://pub.dev/packages/searchable_dropdown

They offer both at once - selecting from the list and searching for a proper item.

**Comment by ManeraKai** [comment]
I tried to do those things without installing additional packages.

**Comment by ManeraKai** [comment]
Note: it won't work in Polish. Just in English. I'll try to fix that.

**Comment by ManeraKai** [comment]
I think it's fixed now.

**Comment by Aga-C** [comment]
It looks better, but I still see some issues:
- Swapping languages doesn't work. Inputs in textfield seems ok, but target language doesn't change.
- I think it would be good to show on the click all the options that are available and later typing text would start filtering them
- Empty space on the beginning of the list doesn't look good
- Autodetect is not on the top of the list anymore and long text of it doesn't wrap (e.g. in Polish it's very long and I can see only part of it)

Are you sure you don't want to use any of the ready solutions? I think it would be easier and faster to achieve full functionality of dropdown-search this way.

**Comment by ManeraKai** [comment]
1. This is fixable
2. It's not shown because a one was typed before. Changing that behavior on the first click is possible though.
3. Is it the padding that your talking about?
![image](https://user-images.githubusercontent.com/40805353/133307974-d5320528-6412-4a45-866c-c49e87e6f17d.png)
4. This is fixable.

5. the AutoComplete widget is so customizable. The app's design is somewhat different from regular android apps. I need that customizability.  However, if it turned out to be complicated. Yeah, I will switch to the packages.

**Comment by Aga-C** [comment]
2. Yes, it would be better from UX point of view.
3. Yes.

**Comment by ManeraKai** [comment]
I've fixed the issues above. However, There is a limitation with AutoComplete that I didn't find a real solution for it yet.
You can see here that the `fromLanguage` options' container can be stretched more to the right:
![image](https://user-images.githubusercontent.com/40805353/133338175-b28fc635-8a2c-46b0-b392-b2bdd52ebc09.png)
However, I can't stretch the `toLanguage` options' container to the left:
![image](https://user-images.githubusercontent.com/40805353/133338229-92da7e49-ff07-4a90-bd22-d84c0144039f.png)
I can't move it behind the red line:
![image](https://user-images.githubusercontent.com/40805353/133338322-a3f2bc8d-877f-4612-8120-ec2c328a6b82.png)
A workaround for it is by wrapping the text:
![image](https://user-images.githubusercontent.com/40805353/133338563-22f1630a-0bf7-485d-a2a5-1597544b5967.png)

**Comment by Aga-C** [comment]
Super, it looks and works good 👍
